### ISSUE TITLE
Multi-Class Brier Score implementation has issues

### ISSUE THREAD

**Issue by jwen307** [IBM/UQ360#14]
The implementation of the multi-class Brier score makes all the targets 1 instead of creating a one-hot vector for each sample. I changed the code to 
`for i in range(len(y_true)):`
 &nbsp;  ` y_target[i, y_true[i]] = 1.0`

instead of `y_target[:, y_true] = 1.0`

**Comment by pronics2004** [comment]
@jwen307  Thanks for catching that!

Would this be a better fix:

`y_target[np.arange(y_true.size), y_true] = 1.0 ` instead of looping?

You are welcome to create a PR for this fix!
